package com.tathvatech.injuryReport.entity;

import java.io.Serializable;
import java.util.Date;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.Table;
@Table(name="injury_after_treatment_master")
public class InjuryAfterTreatment implements Serializable {
    private int pk;
    private String name;
    private String status;
    private Integer createdBy;
    private Date createdDate;
    private Date lastUpdated;

    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getStatus() {
        return status;
    }
    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getCreatedBy()
    {
        return createdBy;
    }
    public void setCreatedBy(Integer createdBy)
    {
        this.createdBy = createdBy;
    }
    public Date getCreatedDate() {
        return createdDate;
    }
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    @Column(autoGenerated=true)
    public int getPk() {
        return pk;
    }
    public void setPk(int pk) {
        this.pk = pk;
    }

    @Column(autoGenerated=true)
    public Date getLastUpdated()
    {
        return lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated)
    {
        this.lastUpdated = lastUpdated;
    }

}

