package com.tathvatech.injuryReport.entity;

import java.io.Serializable;
import java.util.Date;

import com.tathvatech.ts.core.project.LocationTypeOID;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.Table;

@Table(name = "injury_location_master")
public class InjuryLocationMaster implements Serializable
{
    private int pk;
    private String name;
    private String status;
    private Integer parentPk;
    private Date createdDate;
    private Date lastUpdated;

    @Column(autoGenerated = true)
    public int getPk()
    {
        return pk;
    }

    public void setPk(int pk)
    {
        this.pk = pk;
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public Integer getParentPk()
    {
        return parentPk;
    }

    public void setParentPk(Integer parentPk)
    {
        this.parentPk = parentPk;
    }

    public String getStatus()
    {
        return status;
    }

    public void setStatus(String status)
    {
        this.status = status;
    }

    public Date getCreatedDate()
    {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate)
    {
        this.createdDate = createdDate;
    }

    @Column(autoGenerated = true)
    public Date getLastUpdated()
    {
        return lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated)
    {
        this.lastUpdated = lastUpdated;
    }
    public LocationTypeOID getOID()
    {
        return new LocationTypeOID(pk, name);
    }

}

