/*
 * Created on Nov 1, 2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package com.tathvatech.user.entity;

import java.util.Date;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.Table;

/**
 * @author Hari
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
@Table(name="TAB_PROJECT_FORMS")
public class ProjectForm
{
	private int pk;
	private int projectPk;
	private int projectPartPk;
	private Integer workstationPk;
	private int formPk;
	private String name;
	private int appliedByUserFk;
	private Date lastUpdated;
	
	@Column(autoGenerated=true)
    public int getPk()
	{
		return pk;
	}

	public void setPk(int pk)
	{
		this.pk = pk;
	}

	public int getProjectPk()
	{
		return projectPk;
	}

	public void setProjectPk(int projectPk)
	{
		this.projectPk = projectPk;
	}
	
	public int getProjectPartPk() {
		return projectPartPk;
	}

	public void setProjectPartPk(int projectPartPk) {
		this.projectPartPk = projectPartPk;
	}

	public Integer getWorkstationPk() 
	{
		return workstationPk;
	}

	public void setWorkstationPk(Integer workstationPk) 
	{
		this.workstationPk = workstationPk;
	}

	public int getFormPk()
	{
		return formPk;
	}

	public void setFormPk(int formPk)
	{
		this.formPk = formPk;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getAppliedByUserFk() {
		return appliedByUserFk;
	}

	public void setAppliedByUserFk(int appliedByUserFk) {
		this.appliedByUserFk = appliedByUserFk;
	}

	@Column(autoGenerated=true)
	public Date getLastUpdated()
	{
		return lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated)
	{
		this.lastUpdated = lastUpdated;
	}

	public ProjectForm()
    {
        super();
    }
}
