/*
 * Created on Nov 1, 2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package com.tathvatech.user.entity;

import java.util.Date;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.Table;

/**
 * @author Hari
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
@Table(name="TAB_SENDRESPONSE_SETTING")
public class SendResponseSetting
{
	private String pk;
	private int userPk;
	private int surveyPk;
	private String notifyOn;
	private String notifyTo;
	private Date lastUpdated;

	@Column(autoGenerated=true)
	public String getPk()
	{
		return pk;
	}
	public void setPk(String pk)
	{
		this.pk = pk;
	}
	public int getUserPk()
	{
		return userPk;
	}
	public void setUserPk(int userPk)
	{
		this.userPk = userPk;
	}
	public int getSurveyPk()
	{
		return surveyPk;
	}
	public void setSurveyPk(int surveyPk)
	{
		this.surveyPk = surveyPk;
	}
	public String getNotifyOn()
	{
		return notifyOn;
	}
	public void setNotifyOn(String notifyOn)
	{
		this.notifyOn = notifyOn;
	}
	public String getNotifyTo()
	{
		return notifyTo;
	}
	public void setNotifyTo(String notifyTo)
	{
		this.notifyTo = notifyTo;
	}

	@Column(autoGenerated=true)
	public Date getLastUpdated()
	{
		return lastUpdated;
	}
	public void setLastUpdated(Date lastUpdated)
	{
		this.lastUpdated = lastUpdated;
	}

}
