/*
 * Created on Nov 1, 2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package com.tathvatech.user.entity;

import java.util.Date;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.Table;

/**
 * @author Hari
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
@Table(name="TAB_SURVEY_PERMS")
public class SurveyPerms
{
	private int pk;
	private int surveyPk;
	private int userPk;
	private boolean dataEntry;
	private boolean mDataEntry;
	private boolean view;
	private boolean edit;
	private boolean publish;
	private Date lastUpdated;

	@Column(autoGenerated=true)
	public int getPk()
	{
		return pk;
	}
	public void setPk(int pk)
	{
		this.pk = pk;
	}
	public int getSurveyPk()
	{
		return surveyPk;
	}
	public void setSurveyPk(int surveyPk)
	{
		this.surveyPk = surveyPk;
	}
	public int getUserPk()
	{
		return userPk;
	}
	public void setUserPk(int userPk)
	{
		this.userPk = userPk;
	}
	public boolean isDataEntry()
	{
		return dataEntry;
	}
	public void setDataEntry(boolean dataEntry)
	{
		this.dataEntry = dataEntry;
	}
	public boolean ismDataEntry()
	{
		return mDataEntry;
	}
	public void setmDataEntry(boolean mDataEntry)
	{
		this.mDataEntry = mDataEntry;
	}
	public boolean isView()
	{
		return view;
	}
	public void setView(boolean view)
	{
		this.view = view;
	}
	public boolean isEdit()
	{
		return edit;
	}
	public void setEdit(boolean edit)
	{
		this.edit = edit;
	}
	public boolean isPublish()
	{
		return publish;
	}
	public void setPublish(boolean publish)
	{
		this.publish = publish;
	}
	@Column(autoGenerated=true)
	public Date getLastUpdated()
	{
		return lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated)
	{
		this.lastUpdated = lastUpdated;
	}
}