/*
 * Created on Nov 1, 2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package com.tathvatech.user.entity;

import java.util.Date;

import com.tathvatech.ts.core.accounts.UserOID;

import com.tathvatech.user.OID.OID;
import com.tathvatech.user.OID.UserOID;
import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.Table;

/**
 * @author Hari
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
@Table(name="user_preferences_data")
public class UserPreferencesDataBean
{
	private int pk;
	private UserOID userOID;
	private OID anchorEntityOID;
	private String name;
	private String property;
	private String value;
	private Date createdDate;
	private Date lastUpdated;

	@Column(autoGenerated=true)
	public int getPk()
	{
		return pk;
	}
	public void setPk(int pk)
	{
		this.pk = pk;
	}
	public UserOID getUserOID() {
		return userOID;
	}
	public void setUserOID(UserOID userOID) {
		this.userOID = userOID;
	}
	public OID getAnchorEntityOID() {
		return anchorEntityOID;
	}
	public void setAnchorEntityOID(OID anchorEntityOID) {
		this.anchorEntityOID = anchorEntityOID;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public String getProperty()
	{
		return property;
	}
	public void setProperty(String property)
	{
		this.property = property;
	}
	public String getValue()
	{
		return value;
	}
	public void setValue(String value)
	{
		this.value = value;
	}
	@Column(autoGenerated=true)
	public Date getLastUpdated()
	{
		return lastUpdated;
	}
	public void setLastUpdated(Date lastUpdated)
	{
		this.lastUpdated = lastUpdated;
	}
	@Override
	public boolean equals(Object obj) 
	{
		if(obj == null)
			return false;
		return (pk == ((UserPreferencesDataBean)obj).getPk());
	}
	@Override
	public int hashCode() 
	{
		return pk;
	}
}
