/*
 * Created on Nov 1, 2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package com.tathvatech.user.entity;

import java.util.Date;
import java.util.List;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.Table;

import com.tathvatech.ts.caf.db.PersistWrapper;

/**
 * @author Hari
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
@Table(name = "tab_usertypes")
public class UserTypes
{
	private int pk;
	private String name;
	private Date lastUpdated;

	/**
     * 
     */
    public UserTypes()
    {
        super();
    }

	@Column(autoGenerated=true)
	public int getPk()
	{
		return pk;
	}

	public void setPk(int pk)
	{
		this.pk = pk;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(autoGenerated=true)
	public Date getLastUpdated()
	{
		return lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated)
	{
		this.lastUpdated = lastUpdated;
	}
	
	public static List<UserTypes> getAllUserTypes() throws Exception
	{
		return PersistWrapper.readList(UserTypes.class, "select * from tab_usertypes");
	}

}
