/*
 * Created on Nov 1, 2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package com.tathvatech.forms.entity;

import java.util.Date;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.NoColumn;
import net.sf.persist.annotations.Table;

import com.tathvatech.ts.core.accounts.User;

/**
 * @author Hari
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
@Table(name="tab_sectionlock")
public class ObjectLock
{
	private int pk;
	private int responseFk;
	private int formSectionFk;
	private String sectionId;
	private int userPk;
	private Integer attributionUserFk;
	private Date lockDate;
	
	private Date lastUpdated;
	
	private User lockedByUser;
	
	@Column(autoGenerated=true)
	public int getPk()
	{
		return pk;
	}

	public void setPk(int pk)
	{
		this.pk = pk;
	}

	@NoColumn
	public User getLockedByUser()
	{
		return lockedByUser;
	}

	public void setLockedByUser(User lockedByUser)
	{
		this.lockedByUser = lockedByUser;
	}

	public int getResponseFk() {
		return responseFk;
	}

	public void setResponseFk(int responseFk) {
		this.responseFk = responseFk;
	}

	public int getFormSectionFk() {
		return formSectionFk;
	}

	public void setFormSectionFk(int formSectionFk) {
		this.formSectionFk = formSectionFk;
	}

	public String getSectionId()
	{
		return sectionId;
	}

	public void setSectionId(String sectionId)
	{
		this.sectionId = sectionId;
	}

	public int getUserPk()
	{
		return userPk;
	}

	public void setUserPk(int userPk)
	{
		this.userPk = userPk;
	}

	public Integer getAttributionUserFk()
	{
		return attributionUserFk;
	}

	public void setAttributionUserFk(Integer attributionUserFk)
	{
		this.attributionUserFk = attributionUserFk;
	}

	public Date getLockDate()
	{
		return lockDate;
	}

	public void setLockDate(Date lockDate)
	{
		this.lockDate = lockDate;
	}

	@Column(autoGenerated=true)
	public Date getLastUpdated()
	{
		return lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated)
	{
		this.lastUpdated = lastUpdated;
	}

	/**
     * 
     */
    public ObjectLock()
    {
    }
}
