/*
 * Created on Nov 1, 2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package com.tathvatech.forms.entity;

import java.util.Date;



/**
 * @author Hari
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
@Table(name="testproc_form_section")
public class TestProcFormSection
{
	private int pk;
	private int testProcFormAssignFk;
	private long formSectionFk;
	private int createdBy;
	private Date createdDate;
	private Date lastUpdated;
	
	
	@Column(autoGenerated=true)
	public int getPk()
	{
		return pk;
	}

	public void setPk(int pk)
	{
		this.pk = pk;
	}

	public int getTestProcFormAssignFk()
	{
		return testProcFormAssignFk;
	}

	public void setTestProcFormAssignFk(int testProcFormAssignFk)
	{
		this.testProcFormAssignFk = testProcFormAssignFk;
	}

	public long getFormSectionFk()
	{
		return formSectionFk;
	}

	public void setFormSectionFk(long formSectionFk)
	{
		this.formSectionFk = formSectionFk;
	}

	public int getCreatedBy()
	{
		return createdBy;
	}

	public void setCreatedBy(int createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getCreatedDate()
	{
		return createdDate;
	}

	public void setCreatedDate(Date createdDate)
	{
		this.createdDate = createdDate;
	}

	@Column(autoGenerated=true)
	public Date getLastUpdated()
	{
		return lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated)
	{
		this.lastUpdated = lastUpdated;
	}
	
	@Override
	public int hashCode() 
	{
		if (pk == 0)
			return super.hashCode();
		return pk;
	}

	@Override
	public boolean equals(Object obj) {
		if(pk == 0 || obj == null)
			return super.equals(obj);
		return pk == ((TestProcFormSection)obj).getPk();
	}

	public OID getOID()
	{
		return new TestProcSectionOID(pk);
	}

}
