/*
 * Created on Nov 1, 2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package com.tathvatech.unit.entity;

import java.util.Date;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.Table;

import com.tathvatech.ts.caf.db.PersistWrapper;
import com.tathvatech.ts.core.UserContext;
import com.tathvatech.ts.core.common.OID;
import com.thirdi.surveyside.security.Actions;

/**
 * @author Hari
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
@Table(name="entity_actions")
public class EntityActions
{
	private int pk; // this pk goes into the _h records as actionPk, if another object gets an _h records because one object was modified, the same actionId gets both _h records.
	private int objectPk;
	private int objectType;
	private String action1;
	private String action2;
	private String action3;
	private String action4;
	private String action5;
	private Integer performedBy;
	private Date performedDate;
	private Date lastUpdated;
	
	@Column(autoGenerated=true)
	public int getPk()
	{
		return pk;
	}

	public void setPk(int pk)
	{
		this.pk = pk;
	}

	public int getObjectPk()
	{
		return objectPk;
	}

	public void setObjectPk(int objectPk)
	{
		this.objectPk = objectPk;
	}

	public int getObjectType()
	{
		return objectType;
	}

	public void setObjectType(int objectType)
	{
		this.objectType = objectType;
	}

	public String getAction1()
	{
		return action1;
	}

	public void setAction1(String action1)
	{
		this.action1 = action1;
	}

	public String getAction2()
	{
		return action2;
	}

	public void setAction2(String action2)
	{
		this.action2 = action2;
	}

	public String getAction3()
	{
		return action3;
	}

	public void setAction3(String action3)
	{
		this.action3 = action3;
	}

	public String getAction4()
	{
		return action4;
	}

	public void setAction4(String action4)
	{
		this.action4 = action4;
	}

	public String getAction5()
	{
		return action5;
	}

	public void setAction5(String action5)
	{
		this.action5 = action5;
	}

	public Integer getPerformedBy()
	{
		return performedBy;
	}

	public void setPerformedBy(Integer performedBy)
	{
		this.performedBy = performedBy;
	}

	public Date getPerformedDate()
	{
		return performedDate;
	}

	public void setPerformedDate(Date performedDate)
	{
		this.performedDate = performedDate;
	}

	@Column(autoGenerated=true)
	public Date getLastUpdated()
	{
		return lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated)
	{
		this.lastUpdated = lastUpdated;
	}

	public static EntityActions createAction(UserContext context, OID oid, Actions[] actions) throws Exception
	{
		EntityActions act = new EntityActions();
		act.setObjectPk(oid.getPk());
		act.setObjectType(oid.getEntityType().getValue());
		
		if(actions.length > 0)
			act.setAction1(actions[0].name());
		if(actions.length > 1)
			act.setAction2(actions[1].name());
		if(actions.length > 2)
			act.setAction3(actions[2].name());
		if(actions.length > 3)
			act.setAction4(actions[3].name());
		if(actions.length > 4)
			act.setAction5(actions[4].name());
		
		act.setPerformedBy(context.getUser().getPk());
		act.setPerformedDate(new Date());

		int pk = PersistWrapper.createEntity(act);
		return PersistWrapper.readByPrimaryKey(EntityActions.class, pk);
	}
}
