/*
 * Created on Nov 1, 2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package com.tathvatech.unit.entity;

import java.util.Date;

import com.tathvatech.ts.core.common.TestableEntity;
import com.tathvatech.ts.core.part.SupplierOID;
import com.tathvatech.ts.core.sites.SiteGroupOID;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.Table;

/**
 * @author Hari
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
@Table(name="TAB_UNIT")
public class Unit implements TestableEntity
{
	private int pk;
	private int partPk;
	private Integer partRevisionPk;
	private Integer supplierFk;
	private Integer siteGroupFk;
	private int createdBy;
	private Date createdDate;
	private int estatus; 
	private Date lastUpdated;
	
	@Column(autoGenerated=true)
	public int getPk()
	{
		return pk;
	}

	public void setPk(int pk)
	{
		this.pk = pk;
	}

	public int getPartPk() {
		return partPk;
	}

	public void setPartPk(int partPk) {
		this.partPk = partPk;
	}

	public Integer getPartRevisionPk() {
		return partRevisionPk;
	}

	public void setPartRevisionPk(Integer partRevisionPk) {
		this.partRevisionPk = partRevisionPk;
	}

	public Integer getSupplierFk() {
		return supplierFk;
	}

	public void setSupplierFk(Integer supplierFk) {
		this.supplierFk = supplierFk;
	}

	public Integer getSiteGroupFk() {
		return siteGroupFk;
	}

	public void setSiteGroupFk(Integer siteGroupFk) {
		this.siteGroupFk = siteGroupFk;
	}

	public int getCreatedBy()
	{
		return createdBy;
	}

	public void setCreatedBy(int createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getCreatedDate()
	{
		return createdDate;
	}

	public void setCreatedDate(Date createdDate)
	{
		this.createdDate = createdDate;
	}

	public int getEstatus() {
		return estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	@Column(autoGenerated=true)
	public Date getLastUpdated()
	{
		return lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated)
	{
		this.lastUpdated = lastUpdated;
	}

	/**
     * 
     */
    public Unit()
    {
    }


	public Unit(UnitBean unitBean)
	{
		this.setPk(unitBean.getPk());
		this.setPartPk(unitBean.getPartPk());
		this.setPartRevisionPk(unitBean.getPartRevisionPk());
		this.setSupplierFk(unitBean.getSupplierOID().getPk());
		this.setSiteGroupFk(unitBean.getSiteGroupOID().getPk());
		this.setCreatedBy(unitBean.getCreatedBy());
		this.setCreatedDate(unitBean.getCreatedDate());
		this.setLastUpdated(unitBean.getLastUpdated());
	}
	
	public UnitBean getUnitBean(ProjectOID projectOID)
	{
		Date now = new Date();
		UnitH unitH = UnitManagerCore.getUnitH(this.getOID(), now);
		UnitInProject unitInProject = UnitManagerCore.getUnitInProject(this.getOID(), projectOID);
		UnitInProjectH unitInProjectH = UnitManagerCore.getUnitInProjectH(unitInProject.getOID(), now);

		UnitBean unitBean = new UnitBean();
		
		unitBean.setPk(this.getPk());
		unitBean.setPartPk(this.getPartPk());
		unitBean.setPartRevisionPk(this.getPartRevisionPk());
		unitBean.setSupplierOID(new SupplierOID(this.getSupplierFk()));
		unitBean.setSiteGroupOID(new SiteGroupOID(this.getSiteGroupFk()));
		unitBean.setUnitOriginType(UnitOriginType.valueOf(unitInProject.getUnitOriginType()));
		unitBean.setCreatedBy(this.getCreatedBy());
		unitBean.setCreatedDate(this.getCreatedDate());
		unitBean.setLastUpdated(this.getLastUpdated());
		unitBean.setParentPk(unitInProjectH.getParentPk());
		unitBean.setProjectPartPk(unitInProjectH.getProjectPartPk());
		unitBean.setProjectPk(unitInProject.getProjectPk());
		unitBean.setSerialNo(unitH.getSerialNo());
		unitBean.setStatus(unitInProjectH.getStatus());
		unitBean.setUnitDescription(unitH.getUnitDescription());
		unitBean.setUnitName(unitH.getUnitName());
		
		return unitBean;
	}
    
	@Override
	public UnitOID getOID() {
		return new UnitOID(pk, null);
	}
}
