package com.tathvatech.site.entity;

import java.util.Arrays;
import java.util.Date;
import java.util.List;

import com.tathvatech.ts.core.authorization.Action;
import com.tathvatech.ts.core.authorization.Authorizable;
import com.tathvatech.ts.core.authorization.Role;
import com.tathvatech.ts.core.common.EntityType;
import com.tathvatech.ts.core.common.EntityTypeEnum;
import com.tathvatech.ts.core.common.OID;
import com.tathvatech.ts.core.part.ProjectSiteConfigActionsEnum;
import com.tathvatech.ts.core.part.ProjectSiteConfigRolesEnum;
import com.tathvatech.ts.core.project.ProjectSiteConfigOID;
import com.tathvatech.ts.core.sites.Site;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.NoColumn;
import net.sf.persist.annotations.Table;

@Table(name="project_site_config")
public class ProjectSiteConfig implements Authorizable
{
	private int pk;
	private int projectFk;
	private int siteFk;
	private int managerFk;
	private int estatus;
	private Date lastUpdated;
	
	@Column(autoGenerated = true)
	public int getPk() {
		return pk;
	}
	public void setPk(int pk) {
		this.pk = pk;
	}
	public int getProjectFk() {
		return projectFk;
	}
	public void setProjectFk(int projectFk) {
		this.projectFk = projectFk;
	}
	public int getSiteFk() {
		return siteFk;
	}
	public void setSiteFk(int siteFk) {
		this.siteFk = siteFk;
	}
	public int getManagerFk() {
		return managerFk;
	}
	public void setManagerFk(int managerFk) {
		this.managerFk = managerFk;
	}
	public int getEstatus() {
		return estatus;
	}
	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}
	@Column(autoGenerated = true)
	public Date getLastUpdated() {
		return lastUpdated;
	}
	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public OID getOID() 
	{
		Site site = SiteDelegate.getSite(siteFk);
		return new ProjectSiteConfigOID(pk, site.getName());
	}
	@Override
	@NoColumn
	public List<? extends Role> getSupportedRoles() 
	{
		return Arrays.asList(ProjectSiteConfigRolesEnum.values());
	}

	@Override
	@NoColumn
	public List<? extends Action> getSupportedActions() 
	{
		return Arrays.asList(ProjectSiteConfigActionsEnum.values());
	}
	@Override
	public EntityType getEntityType()
	{
		return EntityTypeEnum.ProjectSiteConfig;
	}
	@Override
	public String getDisplayText()
	{
		Site site = SiteDelegate.getSite(siteFk);
		return site.getName();
	}

}
