/*
 * Created on May 21, 2015
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package com.tathvatech.site.entity;

import java.util.Arrays;
import java.util.Date;
import java.util.List;

import com.tathvatech.ts.core.authorization.Action;
import com.tathvatech.ts.core.authorization.Authorizable;
import com.tathvatech.ts.core.authorization.Role;
import com.tathvatech.ts.core.common.EntityType;
import com.tathvatech.ts.core.common.EntityTypeEnum;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.NoColumn;
import net.sf.persist.annotations.Table;

/**
 * @author Hari
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
@Table(name="site_group")
public class SiteGroup implements Authorizable
{
	private int pk;
	private String name;
	private String description;
	private int createdBy;
	private Date createdDate;
	private Date lastUpdated;
	
	@Column(autoGenerated=true)
	public int getPk()
	{
		return pk;
	}

	public void setPk(int pk)
	{
		this.pk = pk;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getCreatedBy()
	{
		return createdBy;
	}

	public void setCreatedBy(int createdBy)
	{
		this.createdBy = createdBy;
	}

	public Date getCreatedDate()
	{
		return createdDate;
	}

	public void setCreatedDate(Date createdDate)
	{
		this.createdDate = createdDate;
	}

	@Column(autoGenerated=true)
	public Date getLastUpdated()
	{
		return lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated)
	{
		this.lastUpdated = lastUpdated;
	}

	/**
     * 
     */
    public SiteGroup()
    {
    }
    
    

	@Override
	public int hashCode() 
	{
		return pk;
	}

	@Override
	public boolean equals(Object obj) {
		if(obj instanceof SiteGroup && ((SiteGroup)obj).getPk() == pk)
			return true;
		
		return false;
	}

	@Override
	@NoColumn
	public List<? extends Role> getSupportedRoles() 
	{
		return Arrays.asList(SiteRolesEnum.values());
	}

	@Override
	@NoColumn
	public List<? extends Action> getSupportedActions() 
	{
		return Arrays.asList(SiteActionsEnum.values());
	}

	public SiteGroupOID getOID() 
	{
		return new SiteGroupOID(pk, name);
	}

	@Override
	public String toString() {
		return name;
	}
	
	public String getDisplayText()
	{
		if(description != null && description.trim().length() > 0)
			return name + " (" + description + ")";
		else
			return name;
	}

	@Override
	public EntityType getEntityType()
	{
		return EntityTypeEnum.SiteGroup;
	}
}
