/*
 * Created on Nov 1, 2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package com.tathvatech.project.entity;

import java.util.Date;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.Table;

/**
 * @author Hari
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
@Table(name="TAB_PROJECT_USERS")
public class ProjectUser
{
	private int pk;
	private int projectPk;
	private int workstationPk;
	private Integer projectPartPk;
	private int userPk;
	private String role;
	private Date lastUpdated;
	
	@Column(autoGenerated=true)
    public int getPk()
	{
		return pk;
	}

	public void setPk(int pk)
	{
		this.pk = pk;
	}

	public int getProjectPk()
	{
		return projectPk;
	}

	public void setProjectPk(int projectPk)
	{
		this.projectPk = projectPk;
	}
	
	public Integer getProjectPartPk() {
		return projectPartPk;
	}

	public void setProjectPartPk(Integer projectPartPk) {
		this.projectPartPk = projectPartPk;
	}

	public int getWorkstationPk() 
	{
		return workstationPk;
	}

	public void setWorkstationPk(int workstationPk) 
	{
		this.workstationPk = workstationPk;
	}

	public int getUserPk()
	{
		return userPk;
	}

	public void setUserPk(int userPk)
	{
		this.userPk = userPk;
	}

	public String getRole()
	{
		return role;
	}

	public void setRole(String role)
	{
		this.role = role;
	}

	@Column(autoGenerated=true)
	public Date getLastUpdated()
	{
		return lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated)
	{
		this.lastUpdated = lastUpdated;
	}

	public ProjectUser()
    {
        super();
    }
}
